### PR TITLE
Fix mesh.begin()

### PR DESCRIPTION
**Pull request by TMRh20**
- Begin will return true by mistake because of recent changes to the renewAddress() function
- See https://github.com/nRF24/RF24Mesh/blob/FixBegin()/RF24Mesh.cpp#L39

### CODE REVIEW

**Review by 2bndy5 — APPROVED** [review]
Damn. How did I miss this one?

**Comment by 2bndy5** [comment]
Oh I didn't see the file name. I thought this was an example. I really should do a search for all calls to `renewAddress()`.

**Comment by 2bndy5** [comment]
That seems to be the last one. This should get a priority release after merging.

**Comment by TMRh20** [comment]
> Damn. How did I miss this one?

I was thinking the same thing. 👍

**Comment by 2bndy5** [comment]
You wanna do the release (& try the fancy new auto-generate summary button)?

**Comment by 2bndy5** [comment]
I pushed the version bump in the lib info files.  I'm publish the release now.

**Pull request merged**
